// ('coffee',
// 'Ameno',
// 'Caffe Ameno',
// 3000,
// '/productImages/CaffeAmeno.png',
// 'Chocolate, Nutty, low acidity',
// 'Cafe Ameno originates from a small bottega in Parma. This coffee blend contains 60% Arabica and 40% Robust. The flavor can be best describe with chocolate mousse and a pistachio ice-cream in the end. This coffee is best as an espresso, but also keeps the pistachio note when you drink it as a cappuccino'),
//   ('coffee',
//   'Diemme',
//   'Diemme',
//   2590,
//   '/productImages/Diemme.webp',
//   'Floral notes, Hazelnut',
//   'This beautiful coffee is 100% Arabica out of Columbia, Brasil, Tanzania and India. Due to its mild roast it is a very elegant light coffee. When you drink it as a Espresso you will see a perfect hazelnut colored crema. If combined with milk, the caramel notes gonna get even stronger and sweeter. A absolute recommendation for everyone who is looking for the perfect beginner coffee'),
//   ('coffee',
//   'Espressoperfetto',
//   'Espresso Perfetto Bar Gusto',
//   2200,
//   '/productImages/EspressoPerfettoBar.webp',
//   'Chocolate, Caramel, Floral',
//   'This powerhouse is 60% Arabica and 40% Robusta. This combination makes the coffee to an absolute special taste experience. Fancier of typical north italian coffee will love this blend. Here, the mild, flowery bouquet of Arabica meets the slightly earthy, bitter Robusta, which is characterized by chocolate and caramel. Pure Italy!'),
//   ('coffee',
//   'Kimbo',
//   'Kimbo Espresso Neopoletan',
//   3190,
//   '/productImages/kimbo-espresso-napoletano-bohnen-1kg-front.webp',
//   'Fruity, Chocolate, Toast',
//   'The powerful blend of the Kimbo Espresso Napoletano is made up of 80% of the finest Arabica beans and 20% of the highest quality Robusta beans. The beans are roasted according to the original Neapolitan tradition, resulting in a dark roast. You will get delicious notes of chocolate, sweet fruit and toast'),
//   ('coffee',
//   'Passalacqua',
//   'Passalacqua Miscela Napoli',
//   4198,
//   '/productImages/passalacqua-miscela-napoli-1kg-vorne_1.webp',
//   'Hazelnut, Caramel, Chocolate',
//   'The  Espresso with the small American Indian in its logo is no unnderdog for italian coffee enthusiast anymore. Behind Passalacqua Miscela Napoli hides a cofee full of character. A long roasting time leads to a very low acidity and to the chocolate taste. This coffee is easy to use.'),
// ('equipment',
// 'imsbasket',
// 'Ims Basket',
// 1990,
// '/equipmentImages/imssieb.png',
// 'Stainless steel, best extraction ',
// 'The stainless steel basket for a perfect extraction and easy cleaning! We recommend the basket for 16-18g of coffee and anyone who wants a really creamy extraction.'),
//   ('equipment',
//   'normcoretamper',
//   'Normcore Tamper',
//   2999,
//   '/equipmentImages/normcoretamper.png',
//   'Spring loaded',
//   'Level Tamping - The ingenious design of leveling plate ensures your tamping level every time by resting on top of the filter basket as you press down on ground coffee. Consistent Pressure - The amount of pressure you apply is simply controlled by a pre-calibrated spring inside the tamper itself. Moreover, it comes with 3 interchangeable springs to suit your preference.'),
//   ('equipment',
//   'normcoreleveler',
//   'Normcore Distributer Tool',
//   1990,
//   '/equipmentImages/leveler.png',
//   'Even Distribution',
//   'Improve your tamping and extractions when coffee grounds are distributed, therefore increased yield and better-tasting espresso. This tool offers a level tamping surface which makes tamping become easier and more consistent.'),
//   ('equipment',
//   'portafilter',
//   'Bottomless Portafilter',
//   7999,
//   '/equipmentImages/portafiler.png',
//   'Watch the extraction process',
//   'A bottomless portafilter is an important piece of equipment that aids in diagnosing espresso extraction issues. The spouts are removed, the basket is exposed, allowing you to watch the entire extraction process. The Bottomless Portafilter sometimes referred to as a Naked Portafilter has become an essential addition to any Barista');
